server:
  port: 8981
spring:
  application:
    name: API-CATE
  cloud:
    nacos:
      discovery:
        server-addr: 121.196.203.51:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.196.203.51:3306/video_project?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cen.admins.entity
logging:
  level:
    com.cen.cate.dao: debug
